import os

class SuperLinterParser:
    def __init__(self, log_file_path):
        """
        Initializes the parser with the path to the Super Linter text log.
        """
        self.log_file_path = log_file_path

    def parse_errors(self):
        """
        Reads the raw text log and extracts only the blocks containing errors,
        ignoring all the standard [INFO] setup steps to save token context.
        """
        if not os.path.exists(self.log_file_path):
            print(f"❌ Parser Error: Log file not found at {self.log_file_path}")
            return None

        print(f"📄 Reading text log from: {self.log_file_path}")

        # Read the raw text log generated by Super Linter
        try:
            with open(self.log_file_path, "r", encoding="utf-8") as f:
                lines = f.readlines()
        except Exception as e:
            print(f"❌ Failed to read log file: {e}")
            return None

        # Extract only the actual error blocks
        errors = []
        is_capturing = False
        current_error_block = ""

        for line in lines:
            # When we see the red error flag, start recording the text
            if "[ERROR]" in line and "Found errors in" in line:
                is_capturing = True
            
            if is_capturing:
                current_error_block += line
                
                # Super Linter ends its error blocks with a generic [INFO] line and a dashed separator
                if "[INFO]" in line and "----------------------------------------------" in line:
                    is_capturing = False
                    errors.append(current_error_block)
                    current_error_block = ""

        # If we found errors, combine them into one string for the AI
        if errors:
            print(f"✅ Parser successfully extracted {len(errors)} error blocks.")
            return "\n".join(errors)
        else:
            print("✅ No errors found in the parsed text log.")
            return None

if __name__ == "__main__":
    # Quick local test block
    print("SuperLinter text parser loaded.")